language: python
python:
  - "3.6"

cache:
  directories:
  - soneson2013

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-4.3.27.1-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set auto_update_conda no
  - travis_retry conda env create --quiet --file environment.yaml

before_script:
  - source activate dsc-soneson-2013
  - conda list
  - dsc --version
  - du -sh soneson2013/
  - ls -lh soneson2013/

script:
  - dsc soneson2013.dsc -h
  - dsc soneson2013.dsc
  - dsc-query soneson2013/ -o metadata.ipynb
  - Rscript queries.R
