name: dsc-soneson-2013
channels:
- conda-forge
- bioconda/label/gcc7
- defaults
- jdblischak
dependencies:
# DSC
- conda-forge::dsc=0.3.3
- conda-forge::r-devtools
- jdblischak::r-dscrutils
# Benchmark
- bioconda/label/gcc7::bioconductor-compcoder
- bioconda/label/gcc7::bioconductor-deseq
- bioconda/label/gcc7::bioconductor-edger
- bioconda/label/gcc7::bioconductor-limma
- bioconda/label/gcc7::r-nbpseq
- conda-forge::r-proc
# Utility
- conda-forge::git
- conda-forge::jupyter
- jdblischak::sos-notebook
# Fix curl/ssl error for DESeq on RCC Midway
- conda-forge::r-base
- conda-forge::r-curl
- conda-forge::r-openssl
- conda-forge::r-rcurl
