name: dsc-soneson-2013
channels:
- conda-forge
- bioconda/label/gcc7
- defaults
- jdblischak
dependencies:
- bioconda/label/gcc7::bioconductor-compcoder
- bioconda/label/gcc7::bioconductor-deseq
- bioconda/label/gcc7::bioconductor-edger
- bioconda/label/gcc7::bioconductor-limma
- conda-forge::dsc=0.3.2
- conda-forge::r-devtools
- jdblischak::r-dscrutils
