name: dsc-soneson-2013
channels:
- conda-forge/label/gcc7
- bioconda/label/gcc7
- defaults
- jdblischak
dependencies:
- bioconductor-compcoder
- bioconductor-deseq
- bioconductor-edger
- bioconductor-limma
- dsc=0.3.2
- r-devtools
- r-dscrutils
