name: dsc-soneson-2013
channels:
- conda-forge
- bioconda/label/gcc7
- defaults
- jdblischak
dependencies:
# DSC
- conda-forge::dsc=0.3.2
- conda-forge::r-devtools
- jdblischak::r-dscrutils
# Benchmark
- bioconda/label/gcc7::bioconductor-compcoder
- bioconda/label/gcc7::bioconductor-deseq
- bioconda/label/gcc7::bioconductor-edger
- bioconda/label/gcc7::bioconductor-limma
- bioconda/label/gcc7::r-nbpseq
- conda-forge::r-proc
# Utility
- conda-forge::jupyter
- jdblischak::sos-notebook
